### ISSUE TITLE
update benchmark results

### ISSUE THREAD

**Issue by tellnobody1** [zero-deps/protobuf-scala-macros#2]
- [x] drop `chill` because it does not support scala 2.13
- [x] drop `scodec` because it is not convenient to work with bytes and case classes
- [x] update versions
- [x] update data model
- [x] add dto definiton to proto file
- [x] benchmark dto model
- [x] add boopickle
- [x] add kryo-macros

**Comment by tellnobody1** [comment]
blocked by https://github.com/twitter/chill/issues/316

**Comment by plokhotnyuk** [comment]
Please, consider adding of a couple efficient binary serializers for Scala:
https://github.com/suzaku-io/boopickle
https://github.com/evolution-gaming/kryo-macros

**Comment by tellnobody1** [comment]
reopen because of #10

**Comment by plokhotnyuk** [comment]
@tellnobody1 Thanks! You can use the `.*jsoniter_scala` filter to run benchmarks for jsoniter-scala only... I'm expecting that DAO results will be improved in 1.5x - 2x times.

Also, results of benchmarks can vary greatly depending of JVMs and their parameters for GC, JIT, etc.. As example sbt-jmh allows to set JVM options for:
1) turning on Graal JIT instead of Hotspot C2 JIT: `-jvmArgsAppend "-XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler"`
2) tuning GC / Hotspot C2 JIT for greater throughput: `-jvmArgsAppend "-XX:+UseParallelGC -XX:MaxInlineLevel=18"`
3) switching to other JVM: `-jvm /usr/lib/jvm/graalvm-ee-19.2.1/bin/java`

**Comment by tellnobody1** [comment]
I re-run all tests on i7. All settings are default because JDK always tweaking default GC and I believe in them 🙂
